name: shap
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - cfitsio=3.470
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - cudatoolkit=11.8.0
  - expat=2.6.2
  - fontconfig=2.14.1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geos=3.8.0
  - geotiff=1.7.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - intel-openmp=2024.1.0
  - joblib=1.4.2
  - jpeg=9e
  - kealib=1.5.0
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libgdal=3.6.2
  - libglib=2.78.4
  - libhwloc=2.9.1
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=12.17
  - libspatialite=5.1.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzip=1.8.0
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - minizip=4.0.3
  - mkl=2024.1.0
  - numba=0.59.1
  - numpy=1.26.4
  - openjpeg=2.4.0
  - openssl=3.3.0
  - pandas=2.2.2
  - pcre2=10.42
  - pip=24.0
  - pixman=0.40.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - pthreads-win32=2.9.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - qhull=2020.2
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - setuptools=69.5.1
  - shap=0.45.1
  - six=1.16.0
  - slicer=0.0.8
  - sqlite=3.45.3
  - tbb=2021.9.0
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tk=8.6.14
  - tqdm=4.66.4
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uriparser=0.9.7
  - vc=14.2
  - vc14_runtime=14.38.33135
  - vs2015_runtime=14.38.33135
  - wheel=0.43.0
  - xerces-c=3.2.4
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - affine==2.4.0
      - alembic==1.17.2
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bottle==0.13.4
      - cads-api-client==1.0.3
      - cdsapi==0.7.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - cftime==1.6.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colorlog==6.10.1
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fiona==1.9.6
      - fonttools==4.53.0
      - fqdn==1.5.1
      - gccm==0.0.0
      - geopandas==0.14.4
      - greenlet==3.3.0
      - h11==0.14.0
      - h5netcdf==1.3.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - ipykernel==6.29.4
      - ipython==8.24.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - libpysal==4.10
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mgwr==2.2.1
      - mistune==3.0.2
      - multiurl==0.3.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.7.1.post1
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - optuna==4.6.0
      - optuna-dashboard==0.20.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas-flavor==0.6.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==0.5.6
      - phenology==0.0.26
      - pillow==10.3.0
      - pingouin==0.5.4
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.45
      - psutil==5.9.8
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - python-json-logger==2.0.7
      - pywin32==306
      - pywinpty==2.0.13
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - raster==0.0.4
      - rasterio==1.4.4
      - referencing==0.35.1
      - requests==2.32.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rioxarray==0.19.0
      - rpds-py==0.18.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shapely==2.0.4
      - sniffio==1.3.1
      - soupsieve==2.5
      - spglm==1.1.0
      - spreg==1.4.2
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - svgwrite==1.4.3
      - tabulate==0.9.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tornado==6.4
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.0
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - xarray==2025.12.0
      - xgboost==2.0.3